#ifndef IMAGE_INCLUDES_H
#define IMAGE_INCLUDES_H

#include "Logo.h"
#include "Start.h"
#include "Legend.h"
#include "Menu.h"
#include "SelectedItem.h"
#include "UnselectedItem.h"
#include "One.h"
#include "Two.h"
#include "Three.h"
#include "Four.h"
#include "Five.h"
#include "Six.h"
#include "Seven.h"
#include "Eight.h"
#include "Flag.h"
#include "Question.h"
#include "Bomb.h"
#include "YouWin.h"
#include "YouLose.h"
#include "Time0.h"
#include "Time1.h"
#include "Time2.h"
#include "Time3.h"
#include "Time4.h"
#include "Time5.h"
#include "Time6.h"
#include "Time7.h"
#include "Time8.h"
#include "Time9.h"
#include "TimeColon.h"
#include "BestScoresPlusExpertPlusInsane.h"
#include "BeginnerPlusIntermediate.h"
#include "LogoSmall.h"

#endif
